### ISSUE TITLE
Use only fenced div syntax custom block

### ISSUE THREAD

**Issue by cderv** [anovabr/mqt#1]
Regarding https://twitter.com/Neuropsic/status/1366459567735988226?s=20

You have the error because you still use block engine
https://github.com/anovabr/mqt/blob/a33e3fd1b5601a6b708656e248679c5ecbfcf780/index.Rmd#L118-L123

The [block engine](https://bookdown.org/yihui/bookdown/custom-blocks.html) will create a LaTeX environment with the type provided. 

[Custom block](https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html) will be more flexible as it will ignore the div unless you want to create a LaTeX environment.

**Comment by anovabr** [comment]
Thanks much for your willingness to help me with that!
I removed all markdown files and just used index.rmd. After reading the instructions, I replaced the `block ` with` ::: {.base data-latex=""} `and did not change anything in style.css 
After trying to render the book, I received the same error.
Please check the gif below:

![first-attempt](https://user-images.githubusercontent.com/32950102/109698498-3aea8880-7b6e-11eb-829c-76572199f55c.gif)


Then, I copied and pasted into [R Markdown this example of the shaded box](https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html#block-shaded), and changed the CSS file to add this info. I've got the same error.
Please check the gif below:

![second-attempt](https://user-images.githubusercontent.com/32950102/109698451-2dcd9980-7b6e-11eb-9686-8b5ce8aabda3.gif)

My third attempt was to copy and paste to R Markdown file this command:
```
\begin{verbatim}
We show some \emph{verbatim} text here.
\end{verbatim}

```
Please check the gif below: 

![third](https://user-images.githubusercontent.com/32950102/109698662-666d7300-7b6e-11eb-858a-1302bb398196.gif)

This last try worked. Therefore, I'm thinking that (1) "style.css" is not the file I should change, (2) I need to insert the custom div (base, etc) into another file, and (3) I always have to use ::: instead of { block, type ...}.

It would be great if you could guide me in this process. This is the first step I do in bookdown. 

Finally, are there any commands that allow me to ignore the ` :::{. base` or `{block} ` and "force" to render as a pdf ?

**Comment by anovabr** [comment]
Christophe Dervieux , I think I understood what's happening!!
After adding to preamble.tex
```
\usepackage{color}
\usepackage{framed}
\setlength{\fboxsep}{.8em}

\newenvironment{blackbox}{
  \definecolor{shadecolor}{rgb}{0, 0, 0}  % black
  \color{white}
  \begin{shaded}}
 {\end{shaded}}
```

and inserting to my Markdowfile: 
```
:::: {.blackbox data-latex=""}
::: {.center data-latex=""}
**NOTICE!**
:::

Thank you for noticing this **new notice**! Your noticing it has
been noted, and _will be reported to the authorities_!
::::

```

It was possible to render the book as pdf!! However, now it's not working with HTML (gitbook format), even after adding to style.css
```
.blackbox {
  padding: 1em;
  background: black;
  color: white;
  border: 2px solid orange;
  border-radius: 10px;
}
div.center {
  text-align: center;
}

```

(1) If I'm in the correct route, for any custom DIV that I have in the .css file, I have to create a new environment in the preamble.tex, right?
(2) How can I use this CSS in both pdf and HTML?

Thanks much!!

**Comment by cderv** [comment]
Regarding the first issue, I was meaning that you could use as it is as other places in the book
https://github.com/anovabr/mqt/blob/a33e3fd1b5601a6b708656e248679c5ecbfcf780/17-regressao_logistica_binaria.Rmd#L94-L99

As there is not `data-latex=""`, it means that the div will be ignore and the book would render in PDF. Without special formatting though because CSS won't apply to LaTeX. 

This is why, if you add `data-latex=""` this will render into LaTeX as an environment block. This means this environment must be defined in a CTAN package, or in your preamble. 

So 
> (1) If I'm in the correct route, for any custom DIV that I have in the .css file, I have to create a new environment in the preamble.tex, right?

If you want to use special environment in LaTeX to have special behavior for your PDF output, yes you need to create a new environmment in preamble. You can just avoid having the fenced divs becoming an environment in LaTeX by not setting the attribute `data-latex=` everything should render ok.

> (2) How can I use this CSS in both pdf and HTML?

You can't make a CSS work for LaTeX output - it is only for HTML output.

Hope it helps.

**Comment by anovabr** [comment]
I have no words to say **thank you!** I changed all syntax and now I can render a pdf file.
However, check this gif below.
When I don't define this new environment in the preamble.tex, I can't get the final result.

It's not annoying at all, but I guess I'm doing something very wrong (because you said that by removing ` data-latex=`  , my pdf will ignore this block and run everything else)

Thank you again for your kind support. 

![last-question](https://user-images.githubusercontent.com/32950102/109871954-85413780-7c4a-11eb-8ebe-af1158b3e906.gif)

**Comment by cderv** [comment]
Are you sure you remove the block engine I mentioned here: https://github.com/anovabr/mqt/issues/1#issue-820215437 ? 

The error means that there is still somewhere the creation of a base environment in LaTeX. I think you are just missing one somewhere.

**Comment by anovabr** [comment]
Thanks again! Yes, I'm running locally. I removed all files but index.rmd and the only latex code is this one:
![image](https://user-images.githubusercontent.com/32950102/109874675-309fbb80-7c4e-11eb-96bb-4669cc70b87c.png)

My preamble.tex tested was this one:
![image](https://user-images.githubusercontent.com/32950102/109874748-47dea900-7c4e-11eb-93f3-1262e7fb05df.png)

and then I added the .base as a new environment.

![image](https://user-images.githubusercontent.com/32950102/109874776-51681100-7c4e-11eb-8727-7ae81222d488.png)


However, if this is a bug or an incorrect use from myself, that's ok! It happens and I'm really happy that you could guide me through this process..

Tomorrow I'll post this on twitter to help the other guy that had the same problem =)

**Comment by cderv** [comment]
Did you publish your source yet ? 

I would like to look into this. I really think there is one other syntax somewhere leading to LaTeX environment. 
You may set `keep_tex: TRUE` for `pdf_book` format, to search into the `.tex` file which part of your code use a `\begin{base}` . This way you may find the culprid in one of the Rmd files. 
Also you should have a `.log` file with information like the line number. 

Could be a block engine, or a `data-latex=""` not remove. Or directly TeX syntax used in the Rmd file.
You add a bunch of `\begin{base}` in your file in the repo. 

I let you look into this to fix it.

**Comment by anovabr** [comment]
Thank you again. I don't know (yet) some common tricks of github. Therefore, I upload the new version of the site here:
https://anovabr.github.io/mqt/ (only index.rmd)
You can see at https://github.com/anovabr/mqt/ what I did locally. I just have a single Rmd file now =) 

IF you go to preamble.tex, you gonna see that I removed all `new environment` before compiling the book. However, this gif below shows what happens when I try to render the book as pdf (same error)


https://user-images.githubusercontent.com/32950102/109877730-21227180-7c52-11eb-9e81-5c346903f48f.mp4

Thank you

**Comment by cderv** [comment]
Which package versions are you using ? You may need to update. 

I clone your repo and I can build to pdf without any error.

**Comment by anovabr** [comment]
Amazing!! I updated all packages and now everything works perfectly. I'm really impressed with your support and kindness in guiding me on this issue.  Thank you so much!

**Comment by cderv** [comment]
I should have thought about updating the package 🤕 I think it was an issue in **rmarkdown** that we fixed later on. I supposed you were up to date. 

Thanks for you shared repo and examples, + gif and videos, it helps being efficient!

**Comment by anovabr** [comment]
Thank you again! I'm very lazy at updating a package, but I learned the lesson this times =) 
Now I'll try to render my book as a doc file as well. Hopefully, it will be easier this time =P
